language: python
python:
  - "2.6"
  - "2.7"

install:
  - "pip install pytest-cov"
  - "pip install pytest-pep8"
  - "pip install python-coveralls"
  - "python setup.py install"

script: "py.test test/unit/ --doctest-modules --pep8 kalibrate -v --cov kalibrate --cov-report term-missing"

after_success:
  -coveralls
