language: python
python:
- '2.6'
- '2.7'
install:
- pip install pytest-cov
- pip install pytest-pep8
- pip install python-coveralls
- python setup.py install
script: py.test test/unit/ --doctest-modules -v --cov kalibrate --cov-report term-missing
after_success: -coveralls
deploy:
  provider: pypi
  user: ashmastaflash
  password:
    secure: UN2lBSqZSmOjEupWXUOD35r+rNrVWMDHnVaLjkpHM2UiPP/YTdMRdTCmlE2gz42frbS4ZqwkJQNq4nWYhOD8Nazyo5Pcsqfa502YqmxOgd3FYqhSkWMAz4CrW08SY7Rgrb930cmtd0z6Nh527namzSQw6w/9ACD9cjrUDAys70GVEWWzHBkunP6aSsGXyOiSHhE9aSGX3Y93t1aCXfB7l6EAHNXHnOkCHjNK9qk8KfGY4tdapOMmhZHdcJ61Dt0H+Zwsr/Ce2Q8QzKwQuIEDIm0d7cvsCuMs+5Li2swS1+qQ3bqy5HTxGhvCqnwwOClPXf4mnyMJxLSdfNAnRnyIgRt7Wn+lubV6R7e/iiU+AuzxMWjEJOn9BvioXMCbP2BlXJpkYY+lxLCtegOohXccb6UnbbMu7B0SUyYFQLZb3bgUpEQvPlnXfcANXz7IEqtZ8iyQY4DRKQh41xUKDEZdAmLgdgRBB5BocaWMEBFvQyn35aqYORKCEkYy2E+/5+joY73ALNGcWaXf7zvnOSYYzB3egmMHzllPM4AI2b+9vNTc1wS14uqc68EhfAjuGJZ0q65UPRZPLqUSUUURXhzTOA83AUEh+hrnbJaCJn3oY57LzB1xRL7PpQef5jTweyTXW8kETj9dNI3nb3jFN2pqXa59seyUjirQshNc1smEuYA=
  on:
    tags: true
    repo: ashmastaflash/kal-wrapper
